
package com.netsuite.webservices.platform_2022_1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "exceededConcurrentRequestLimitFault", targetNamespace = "urn:faults_2022_1.platform.webservices.netsuite.com")
public class ExceededConcurrentRequestLimitFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.netsuite.webservices.platform.faults_2022_1.ExceededConcurrentRequestLimitFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ExceededConcurrentRequestLimitFault(String message, com.netsuite.webservices.platform.faults_2022_1.ExceededConcurrentRequestLimitFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ExceededConcurrentRequestLimitFault(String message, com.netsuite.webservices.platform.faults_2022_1.ExceededConcurrentRequestLimitFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.netsuite.webservices.platform.faults_2022_1.ExceededConcurrentRequestLimitFault
     */
    public com.netsuite.webservices.platform.faults_2022_1.ExceededConcurrentRequestLimitFault getFaultInfo() {
        return faultInfo;
    }

}
