
package com.netsuite.webservices.platform_2022_1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "invalidCredentialsFault", targetNamespace = "urn:faults_2022_1.platform.webservices.netsuite.com")
public class InvalidCredentialsFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.netsuite.webservices.platform.faults_2022_1.InvalidCredentialsFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidCredentialsFault(String message, com.netsuite.webservices.platform.faults_2022_1.InvalidCredentialsFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvalidCredentialsFault(String message, com.netsuite.webservices.platform.faults_2022_1.InvalidCredentialsFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.netsuite.webservices.platform.faults_2022_1.InvalidCredentialsFault
     */
    public com.netsuite.webservices.platform.faults_2022_1.InvalidCredentialsFault getFaultInfo() {
        return faultInfo;
    }

}
